/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Define os ponteiros para os Registradores RCC_APB2ENR, GPIOC_CRH e GPIOC_ODR
	uint32_t *pRCC_APB2ENR = (uint32_t)0x40021018;
	uint32_t *pGPIOC_CRH = (uint32_t)0x40011004;
	uint32_t *pGPIOC_ODR = (uint32_t)0x4001100C;

	//1. Habilita o clock da Porta C
	*pRCC_APB2ENR |= 0x10;
	//CNF13[23:22] = 00 e MODE13[21:20] = 10
	//2a. Reseta os bits [23:20]
	*pGPIOC_CRH &= 0xFF0FFFFF;
	//2b. Seta o bit [21]
	*pGPIOC_CRH |= 0x00200000;
	//3. Seta o pino 13 da Porta C (apaga o LED)
	*pGPIOC_ODR |= 0x00002000;

	for(;;)
	{
		//Delay para ver o LED piscar
		for (uint32_t i = 0; i < 500000; i++);
		//Reseta o pino 13 da Porta C (acende o LED)
		*pGPIOC_ODR &= 0xFFFFDFFF;
		//Delay para ver o LED piscar
		for (uint32_t i = 0; i < 500000; i++);
		//Seta o pino 13 da Porta C (apaga o LED)
		*pGPIOC_ODR |= 0x00002000;
	}
}
